employee/urls.py
from django.urls import path
from employee import views

urlpatterns=[
    # path('index',views.index),
    # path('login',views.login),
    # path("signup",views.registration)
    # path('index',views.IndexView.as_view()),
    # path('login',views.LoginView.as_view()),
    # path('signup',views.RegistrationView.as_view()),
    # path('profile/add',views.EmployeeCreateView.as_view(),name="emp-add")
    path('add',views.EmployeeCreateView.as_view(),name="emp-add"),
    path('all',views.EmployeeListView.as_view(),name="emp-list"),
    path('details/<str:emp_id>',views.EmployeeDetailView.as_view(),name="emp-detail"),
    path('change/<str:e_id>',views.EmployeeEditView.as_view(),name='emp-edit'),
    path('remove/<str:e_id>',views.remove_employee,name='emp-remove')
]

employeemgmt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include('employee.urls')),
    path('calculator/',include('calculator.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # to display static files

#css,javascipt,image,audio,video all are given in static files

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eid=models.CharField(max_length=120,primary_key=True)
    profile_pic=models.ImageField(upload_to="profilepics",null=True)
    employee_name=models.CharField(max_length=120)
    designation=models.CharField(max_length=120)
    salary=models.PositiveIntegerField()
    email=models.EmailField(unique=True)
    experience=models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.employee_name
# null=True means even if the field is not filled ,no problem
# python manage.py makemigrations    ->generate a query file in migrations
# python manage.py migrate           ->Apply changes to database
# DJANGO ORM:to interact with the database
# CRUD
# create
# retrive
# update
# delete
# shell to try orm query->python manage.py shell
# next import Employee model(model you want to interact with)->from employee.models import Employee
# creating an employee object
# pythom -m pip install pillow

employee/forms.py
from django import forms
from employee.models import Employee

# class EmployeeForm(forms.Form):
#     eid=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","placeholder":"enter id"}))
#     employee_name=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
#     designation=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
#     salary=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))
#     email=forms.EmailField(widget=forms.EmailInput(attrs={"class":"form-control"}))
#     experience=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))
#     def clean(self):
#         cleaned_data=super().clean()
#         exp=cleaned_data.get("experience")
#         if exp<0:
#             msg="invalid exp"
#             self.add_error("experience",msg)

# class EmployeeCreateForm(forms.Form):
#     eid=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
#     employee_name=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
#     designation=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
#     salary=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))
#     email=forms.EmailField(widget=forms.EmailInput(attrs={"class":"form-control"}))
#     experience=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields='__all__'

        widgets={
            "eid":forms.TextInput(attrs={"class":"form-control"}),
            "employee_name":forms.TextInput(attrs={"class":"form-control"}),
            "designation":forms.TextInput(attrs={"class":"form-control"}),
            "salary":forms.NumberInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control"}),
            "experience":forms.NumberInput(attrs={"class":"form-control"})
        }

#image upload and display

#ModelForm is a class used to create a form equivalent to the model
#here we are styling the form

employee/views.py
# from django.shortcuts import render,redirect
# from django.http import HttpResponse #import class HttpResponse from module http
# from django.views.generic import View  #View is the parentclass of all views
# from employee.forms import EmployeeForm
# from django.contrib import messages
# Create your views here.
#function based views
#class based views
#class based views are better ,we get oops features

#function based view
# def index(request):
#
# def login(request):
#     print("*******************",request.method)
#     return render(request,'login.html')
#
# def registration(request):
#     return render(request,'reg.html')

#class based views
# class IndexView(View):
#     def get(self,request):                       # View is the parent class of all views
#         return render(request,'index.html')
#
# class LoginView(View):                           # if request is get method,return login.html page
#     def get(self,request):                       # View is the parent class of all views
#         return render(request,'login.html')
#     def post(self,request):
#         print(request.POST.get('u_name'))
#         print(request.POST.get('pwd'))
#         return render(request,'login.html')
#
#
#
# class RegistrationView(View):
#     def get(self,request):
#         return render(request,'reg.html')
#
#     def post(self,request):
#         print(request.POST)                #it will give a dictionary
#         print(request.POST.get('f_name'))
#         print(request.POST.get('l_name'))
#         print(request.POST.get('e_mail'))
#         print(request.POST.get('pwd'))
#         print(request.POST.get('u_name'))
#         return render(request,'reg.html')

# class EmployeeCreateView(View):
#     form_class=EmployeeForm            #try to use same variable names like form_class and template_name always
#     template_name="emp-add.html"
#     def get(self,request):
#         form=self.form_class()
#         return render(request,self.template_name,{'form':form})
#     def post(self,request):
#         form=self.form_class(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             print(form.cleaned_data.get("eid"))
#             print(form.cleaned_data.get("employee_name"))
#             print(form.cleaned_data.get("designation"))
#             messages.success(request,"profile has been added")
#             return redirect("emp-add")                 #name=emp-add in the urlsand get method of that view will work
#         else:
#             messages.error(request,"profile adding failed")
#             return render(request,self.template_name,{"form":form})

from django.shortcuts import render,redirect
from employee.models import Employee
from django.contrib import messages
from django.views.generic import View
from employee.forms import EmployeeCreateForm

class EmployeeCreateView(View):
    def get(self,request,*args,**kwargs):                               #*args(list),**kwargs(dict)
        form=EmployeeCreateForm()
        return render(request,'add-nemp.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=EmployeeCreateForm(request.POST,files=request.FILES)     #files=request.FILES  ->for images
        if form.is_valid():
            form.save()
            # print(form.cleaned_data)
            # Employee.objects.create(
            #     eid=form.cleaned_data.get("eid"),
            #     employee_name=form.cleaned_data.get("employee_name"),
            #     designation=form.cleaned_data.get("designation"),
            #     salary=form.cleaned_data.get("salary"),
            #     email=form.cleaned_data.get("email"),
            #     experience=form.cleaned_data.get("experience")
            # )
            messages.success(request,"employee has been added")
            return redirect('emp-add')                           #emp-add is the name we given in urls
        else:
            messages.error(request,"employee added failed")
            return render(request,'add-nemp.html',{'form':form})
        
class EmployeeListView(View):
    def get(self,request,*args,**kwargs):
        qs=Employee.objects.all()
        return render(request,'emp-list.html',{'employees':qs})

class EmployeeDetailView(View):
    def get(self,request,*args,**kwargs):
        qs=Employee.objects.get(eid=kwargs.get('emp_id'))
        return render(request,'emp-detail.html',{'employee':qs})          #print(kwargs)->{'emp_id':'emp_100'}

class EmployeeEditView(View):
    def get(self,request,*args,**kwargs):
        eid=kwargs.get("e_id")
        employee=Employee.objects.get(eid=eid)
        form=EmployeeCreateForm(instance=employee)
        return render(request,'emp-edit.html',{'form':form})
    def post(self,request,*args,**kwargs):
        eid = kwargs.get("e_id")
        employee = Employee.objects.get(eid=eid)
        form = EmployeeCreateForm(request.POST,instance=employee,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "employee has been updated")
            return redirect('emp-add')                        # emp-add is the name we given in urls
        else:
            messages.error(request, "employee updating failed")
            return render(request, 'emp-add.html', {'form': form})

def remove_employee(request,*args,**kwargs):
    eid = kwargs.get("e_id")
    employee = Employee.objects.get(eid=eid)
    employee.delete()
    messages.error(request,"employee has been removed")
    return redirect('emp-list')

employee/templates/add-nemp.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script></head>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>
<body>
<div class="container">
    <form action="{%url 'emp-add' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
        <div class="row">
            <div class="col-4">
                <input type="file" name="profile_pic" id="id_profile_pic" placeholder="Enter profile pic">
            </div>
            <div class="col-4">
                <input type="text" name="eid" id="id_eid" placeholder="Enter employee id">
                <input type="text" name="employee_name" id="id_employee_name" placeholder="Employee name">
                <input type="text" name="designation" id="id_designation" placeholder="Designation">
            </div>
            <div class="col-4">
                <input type="text" name="salary" id="id_salary" placeholder="salary">
                <input type="text" name="email" id="id_email" placeholder="Email">
                <input type="text" name="experience" id="id_experience" placeholder="Experience">
            </div>
        </div>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4"></div>
            <div class="col-4"></div>
        </div>
        <input type="submit">
    </form>

</div>

</body>
</html>

employee/templates/emp-add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script></head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages %}
                {%for msg in messages%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
                       <div class="alert alert-success" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                       <div class="alert alert-danger" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}                   #key given in views
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

</body>
</html>

employee/templates/emp-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div class="card" style="width: 18rem;">
  <img src="{{employee.profile_pic.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{employee.employee_name}}</h5>
    <p class="card-text"></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{employee.designation}}</li>
    <li class="list-group-item">{{employee.salary}}</li>
    <li class="list-group-item">{{employee.email}}</li>
      <li class="list-group-item">{{employee.experience}}</li>
      <li class="list-group-item">{{employee.eid}}</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link"></a>
    <a href="#" class="card-link"></a>
  </div>
</div>
        </div>
        <div class="col-4"></div>
    </div>
</div>

</body>
</html>

employee/templates/emp-edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script></head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages %}
                {%for msg in messages%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
                       <div class="alert alert-success" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                       <div class="alert alert-danger" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}
                {{form.as_p}}                   #key given in views
                <input type="submit">
            </form>
        </div>
        <div class="col-4"></div>
    </div>
</div>

</body>
</html>

employee/templates/emp-list.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            {%if messages %}
                {%for msg in messages%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
                       <div class="alert alert-success" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                    {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                       <div class="alert alert-danger" role="alert">
                    {{msg}}
                           </div>
                    {%endif%}
                {%endfor%}
            {%endif%}
        </div>
        <div class="col-4"></div>
    </div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <table class="table">
                <tr>
                    <th>Employee Id</th>
                    <th>Employee Name</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>

                {%for emp in employees%}
                <tr>
                    <td>{{emp.eid}}</td>
                    <td>{{emp.employee_name}}</td>
                    <td>{{emp.email}}</td>
                    <td>
                        <a href="{%url 'emp-detail' emp.eid%}">view</a>
                        <a href="{%url 'emp-edit' emp.eid%}">edit</a>
                        <a href="{%url 'emp-remove' emp.eid%}">delete</a>
                    </td>
                </tr>
                {%endfor%}
            </table>


        </div>
        <div class="col-2"></div>
    </div>
</div>

</body>
</html>

employee/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>HOME PAGE</h1>

</body>
</html>

employee/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>HOME PAGE</h1>

</body>
</html>

employee/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h1>login</h1>
            <div class="border border-primary">
            <p>login here</p>
                <form action="" method="post">{%csrf_token%}
                <div class="mb-3">
                        <input type="text" placeholder="username" class="form-control" name="u_name">
                    </div>
                <div class="mb-3">
                        <input type="text" placeholder="password" class="form-control" name="pwd">
                    </div>
                    <input type="submit">
                    </form>
                </div>
        </div>
    </div>
</div>

</body>
</html>

employee/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h1>registration</h1>
            <div class="border border-primary">
            <p>register here</p>
                <form action="" method="post">
                    {% csrf_token %}            # All post  forms should have csrf token
                    {{form}}
<!--                    <div class="mb-3">-->
<!--                        <input type="text" placeholder="firstname" class="form-control" name="f_name">-->
<!--                    </div>-->
<!--                    <div class="mb-3">-->
<!--                        <input type="text" placeholder="lastname" class="form-control" name="l_name">-->
<!--                    </div>-->
<!--                    <div class="mb-3">-->
<!--                        <input type="text" placeholder="email" class="form-control" name="e_mail">-->
<!--                    </div>-->
<!--                    <div class="mb-3">-->
<!--                        <input type="text" placeholder="username" class="form-control" name="u_name">-->
<!--                    </div>-->
<!--                    <div class="mb-3">-->
<!--                        <input type="password" placeholder="password" class="form-control" name="pwd">-->
<!--                    </div>-->
                    <div>
                    <input type="submit">
                        </div>
                </form>
                </div>
        </div>
    </div>
</div>


</body>
</html>


# we should give name property to get it to views